### PR TITLE
Migrate PR #164 from Arista Child Repo

### PR DESCRIPTION
**Pull request by qduk**
[This](https://github.com/nautobot/nautobot-plugin-ssot-arista-cloudvision/pull/164) was the PR from the child repo.

### CODE REVIEW

**Comment by qduk** [comment]
> LGTM, could you add as a co-author the initial author?

I've messaged him on the public slack as I don't have his email to co-author him. I'll update this once he responds.

**Comment by Kircheneer** [comment]
@qduk any update on adding the co-author?

**Comment by jdrew82** [comment]
@Kircheneer I've reached out to him and notified him of this PR.

**Comment by jdrew82** [comment]
As we've attempted to give credit to @Eric-Jckson a few times for this PR and he's failed to respond I've added a comment into the code with reference to the original PR. Will merge this one tests are passing.

**Pull request merged**
