### PR TITLE
Reverts ChatOps dependency removal

### PR DESCRIPTION
**Pull request by snaselj**
# Closes NaN

Reverts ChatOps dependency removal, to enable IPFabric ChatOps worker. This is blocked by Python 3.7 support. After Python 3.7 support will be dropped, this PR can be merged.

## What's Changed

- Added `nautobot-chatops[ipfabric]` development dependency.

### CODE REVIEW

**Review by chadell — COMMENTED** [review]
it looks good, should we generate the poetry.lock for that?

**Comment by snaselj** [comment]
> it looks good, should we generate the poetry.lock for that?

I would rather generate `poetry.lock` before getting this PR ready for review to avoid possible conflicts.

**Comment by jdrew82** [comment]
This looks good to me. Can we get it updated for latest pyproject.toml and poetry.lock @snaselj ?

**Review by jdrew82 — APPROVED** [review]
LGTM!

**Pull request merged**
