### PR TITLE
bug #266

### PR DESCRIPTION
**Pull request by gerardocastaldo**
Resolution bug #266

### CODE REVIEW

**Comment by Kircheneer** [comment]
The CI failure is unrelated, I will see if I can fix this separately.

**Comment by gerardocastaldo** [comment]
Hi @Kircheneer , Forgive me, I've never created a pull request.

Thanks for you support.

**Comment by Kircheneer** [comment]
> Hi @Kircheneer , Forgive me, I've never created a pull request.
> 
> Thanks for you support.

Oh no worries, the failing CI in this case is not your fault - its failing in an unrelated piece of code. I just wanted to let you know that this is nothing for you to worry about. Thanks for the submission!

**Review by gerardocastaldo — COMMENTED** [review]
Sync Fork and review

**Comment by gerardocastaldo** [comment]
Hi @Kircheneer , I synced the fork but I don't know if I have to do other to submit newly the pull request.

**Comment by Kircheneer** [comment]
I don't think you need to re-submit, looking good so far. If the CI passed I think we're good to merge. 🚀

**Pull request merged**
