### PR TITLE
Add support for Nautobot 1.2.0 changes around job result views.

### LINKED ISSUE #17: Support Nautobot 1.2.0
### Environment
* Nautobot version:  1.2.0
* nautobot-ssot version:  1.0.1

### Proposed Functionality

Add support for the new JobLogEntry table.

### Use Case

If Nautobot 1.2.0 is installed, the Job Logs within the SSOT Sync page will not load.

### PR DESCRIPTION
**Pull request by smk4664**
Fixes #17

### CODE REVIEW

**Comment by glennmatthews** [comment]
Shouldn't be needed in 1.2.2 and later thanks to the changes made in https://github.com/nautobot/nautobot/pull/1200. Personally I'm OK with this not working exactly as desired under 1.2.0 and 1.2.1, more incentive to update to latest patch releases. ;-)

**Comment by smk4664** [comment]
That is fine with me, I will update the readme or docs to point that out, and leave the test changes in.

**Comment by chadell** [comment]
@smk4664 good to close?

**Comment by smk4664** [comment]
The docs update never went in, and tests need updated for 1.3.x. I will put some time in next week to finish this up.

**Comment by jdrew82** [comment]
@smk4664 This is almost a year old now. I'm going to close out for now and we can revisit/reopen if we deem it necessary.

**Pull request closed without merging**
